baseURL: https://blog.laoqi.cc/
languageCode: en-us
title: QiBlog
theme: PaperMod

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: true
buildFuture: true
buildExpired: true

paginate: 10 # articles per page

minify:
  disableXML: true
  minifyOutput: true

permalinks:
    post: "/:slug/"

defaultContentLanguage: en # prefer language
defaultContentLanguageInSubdir: true


# menu:
#   main:
#     - identifier: categories
#       name: categories
#       url: /categories/
#       weight: 10
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 20
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search